Add information about database file sizes
maxmind/dev-site pull request #1150
Opened 2024-06-26 13:04 UTC by christophermluna

2024-06-26 15:33 UTC, christophermluna commented
not sure how to add the table CSS to the table generated by `DatabaseSizes`

2024-07-01 15:04 UTC, dhogan8 requested changes

2024-07-01 15:04 UTC, dhogan8 commented on src/components/DatabaseSizes.tsx
> +    daterange: string;
We should be using camel case here.

```suggestion
    databaseChanges: {
      csvSizeRange: string;
      databaseName: string;
      ipv4Range: string;
      ipv6Range: string;
      mmdbSizeRange: string;
    }[];
    dateRange: string;
```

2024-07-01 15:04 UTC, dhogan8 commented on src/components/DatabaseSizes.tsx
> +  const databasechangesItems = databasechanges.map((databasechange) => (
```suggestion
  const databaseChangesItems = databaseChanges.map((databaseChange) => (
```

2024-07-01 15:04 UTC, dhogan8 commented
Tagging @kevcenteno for awareness about the GeoIP documentation updates.

2024-07-01 15:48 UTC, christophermluna commented
sorry, @dhogan8, do you mind taking a look at this error? i have looked, but i think that `databaseChanges` is defined

2024-07-01 17:13 UTC, dhogan8 approved these changes

2024-07-01 17:56 UTC, merged