Risk reasons outputs
maxmind/dev-site pull request #1177
Opened 2024-08-20 18:30 UTC by marselester

2024-08-21 21:09 UTC, ugexe commented on content/minfraud/api-documentation/_schemas/ResponseRiskReason.mdx
> +  This object contains risk score reasons for a given transaction that change the risk score significantly.
> This object contains risk score reasons

Is it correct for this to be plural? Or should it be e.g. `This object contains a risk score reason`

2024-08-22 15:19 UTC, ugexe commented
LGTM - I'll wait on approving it until closer to the release since the extra review I added wouldn't prevent merging for this repo

2024-08-26 17:02 UTC, oschwald requested changes

2024-08-26 17:02 UTC, oschwald commented on content/minfraud/api-documentation/_schemas/ResponseRiskReasons.mdx
> +[risk score reason objects](#schema--response--risk-score-reason).
Could we also add the new language here as well?

2024-08-26 20:46 UTC, ugexe approved these changes

2024-08-26 20:47 UTC, merged