[WIP] Add GeoIP docs
maxmind/dev-site pull request #142
Opened 2021-03-22 15:03 UTC by wesrice

2021-03-31 19:51 UTC, kevcenteno requested changes
Just a few small changes.  Also, there's a build failure

2021-03-31 19:51 UTC, kevcenteno commented on content/geoip/docs/web-services/_examples/geolite.json
> +curl -X POST \
This file isn't needed

2021-03-31 19:51 UTC, kevcenteno commented on content/geoip/docs/web-services.mdx
> +  [What's New in GeoIP2](https://dev.maxmind.com/geoip/geoip2/whats-new-in-geoip2/)
Can we add a TODO message here?

2021-03-31 19:51 UTC, kevcenteno commented on content/geoip/docs/web-services/requests.mdx
> +The **geoip.maxmind.com** hostname automatically picks the data center
Let's wrap this in backticks instead of `**`

2021-03-31 19:51 UTC, kevcenteno commented on content/geoip/docs/web-services/requests.mdx
> +The **geolite.info** hostname automatically picks the data center
Let's wrap this in backticks instead of `**`

2021-03-31 20:17 UTC, kevcenteno commented on content/geoip/docs/web-services.mdx
> +  [What's New in GeoIP2](https://dev.maxmind.com/geoip/geoip2/whats-new-in-geoip2/)
Or maybe remove this alert

2021-04-05 15:08 UTC, wesrice commented
@kevcenteno I cleaned this up.

There was an issue with our build script (CSP css file generation) that I fixed. I noticed a new warning output from Gatsby.

```
warn Unsafe builtin method was used, future builds will need to rebuild all pages
warn WebpackError: Unsafe builtin usage fs.writeFileSync
    at dev-site/src/gatsby/gatsby-ssr/replaceRenderer.tsx:61:3
    at dev-site/.cache/api-runner-ssr.js:57:41
    at dev-site/.cache/api-runner-ssr.js:52:25
    at dev-site/.cache/static-entry.js:247:5
    at dev-site/node_modules/@babel/runtime/helpers/interopRequireWildcard.js:19:1
```

The build still completes successfully, but this is something to keep an eye on and potentially revisit.

2021-04-05 15:21 UTC, merged