Add query string to all internal URLs
maxmind/dev-site pull request #212
Opened 2021-06-10 20:11 UTC by kevcenteno

2021-06-11 15:02 UTC, wesrice commented on src/components/Schema/Property.spec.tsx
> +import Link from '..//Link';
`//` => `/`

2021-06-11 15:03 UTC, wesrice requested changes
Looks good. One small change request.

2021-06-11 20:11 UTC, kevcenteno commented on src/components/Schema/Property.spec.tsx
> +import Link from '..//Link';
Good catch. I pushed the correction

2021-06-14 14:46 UTC, wesrice approved these changes

2021-06-14 14:46 UTC, merged