Duplicate integrations
maxmind/dev-site pull request #237
Opened 2021-07-21 15:58 UTC by christophermluna

Make one canonical location for the API and Integration tables for GeoIP2 DBs, link to that location from the Quick Start Guide.

2021-07-21 20:26 UTC, kevcenteno commented
While we're here, can we also do the same thing for /geoip/geolocate-an-ip-/web-services -> /geoip/docs/web-services.mdx

2021-07-22 16:06 UTC, christophermluna commented
> While we're here, can we also do the same thing for /geoip/geolocate-an-ip-/web-services -> /geoip/docs/web-services.mdx

should be taken care of in this recent push.

2021-07-22 19:36 UTC, kevcenteno requested changes

2021-07-22 19:36 UTC, kevcenteno commented on content/geoip/geolocate-an-ip/databases.mdx
> +You can find a complete list of official and unofficial client APIs, and
This can be replaced by the `<APIs />` component

2021-07-29 18:32 UTC, kevcenteno approved these changes

2021-07-29 18:32 UTC, merged