Wes/overview mdx
maxmind/dev-site pull request #69
Opened 2021-01-05 15:41 UTC by wesrice

2021-01-14 22:07 UTC, kevcenteno requested changes
This is quite the PR.  Lots of ideas were implemented here.  I have just a few change requests.

In general, how do you determine which components should have an a11y test (`<Overview>`) and which should not (`<LinkGroup[*]>`)?

2021-01-14 22:15 UTC, wesrice commented on content/geoip2/legacy/_alert.mdx
> +<Alert type="error">
So Gatsby will ignore the file and prevent it from making a page of it. This is custom functionality, but I used the same convention as scss.

https://github.com/maxmind/dev-site/pull/69/files#diff-24c29bd216c07004f4714e6285d1569e3ccf831b89ca9e49b94d05ac8682592eR26

2021-01-15 19:26 UTC, wesrice commented
@kevcenteno I've made the requested changes.

I'm still figuring out when to add a11y tests. Generally, if a component has state changes, I try to add a test to that component. Otherwise, I've just been adding a11y to some to the broader components that integrates a lot of the smaller ones, like the overview template component.

2021-01-15 19:54 UTC, wesrice commented on content/minfraud/index.mdx
> +{/*<!-- lint disable code-block-style -->*/}
I disabled it. Remark lint was confusing indention within react components as indented markdown code blocks.

2021-01-15 21:34 UTC, kevcenteno approved these changes

2021-01-15 21:34 UTC, merged

2021-01-15 22:42 UTC, kevcenteno commented on content/minfraud/index.mdx
> +{/*<!-- lint disable code-block-style -->*/}
I see. It looks like the `fix:content` is also broken; it's adding fence blocks to some of the `<LinkGroup>` occurrences in the mdx files